### ISSUE TITLE
Document using Release Drafter with GitHub Actions

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/.github#20]
Using GitHub Actions might be a good alternative to Release Drafter SaaS in some cases. It would be great to document it in release-drafter.adoc as an advanced use-cas

* GitHub Actions configuration: https://github.com/jenkinsci/gradle-plugin/blob/master/.github/workflows/release-drafter.yml

**Comment by casz** [comment]
See https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/.github/workflows/release-management.yml as well :)

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/.github/pull/23
