### ISSUE TITLE
Setup CI for the Release Drafter configuration

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/.github#21]
I have already broken Release Drafter in Jenkins few times. It would be great to have some kind of CI offered for it.

- [ ] There is a schema for the Release Drafter configuration (https://github.com/toolmantim/release-drafter/issues/311)
- [ ] There is a Jenkins Pipeline step which invokes the schema validation

**Comment by PierreBtz** [comment]
This is blocked by https://github.com/release-drafter/release-drafter/pull/600, the provided schema was not following the draft 04 spec, therefore no validation could be done :/

**Comment by PierreBtz** [comment]
@oleg-nenashev I started to write something to address the validation in #39 . It's a pretty basic bash script, I was just curious what to expect from a json/yaml validator... Let me know if you had something else in mind I will drop this :)
