### ISSUE TITLE
Release Drafter "Changes" title looks odd

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/.github#5]
Currently Release Drafter generates the following output:

```
## Changes
## 🚀 New features and improvements

* [JENKINS-57425](https://issues.jenkins-ci.org/browse/JENKINS-57425) - Add profile to run benchmarks only when the `benchmark` property is set (#206) @AbhyudayaSharma

```

`## Changes` section is designed for uncategorized commits, but we usually do not have ones. I suggest dropping it from the default template

CC @casz @halkeye @timja

**Comment by casz** [comment]
I'm fine with it, I left it there as a reminder to use it as a spot to write something beyond the pull request titles (see https://github.com/jenkinsci/configuration-as-code-plugin/releases/tag/configuration-as-code-1.18 example). :sweat_smile:

**Comment by oleg-nenashev** [comment]
Fair point. What if we add `<!-- Optional: add a release summary here -->` instead? In such case it will appear for maintainers but not for changelog viewers

**Comment by casz** [comment]
Sounds good too :+1:

**Comment by oleg-nenashev** [comment]
Tested in https://github.com/librecores/.github/blob/master/.github/release-drafter.yml , works well

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/.github/pull/6

**Comment by oleg-nenashev** [comment]
Should work now
